# -*- ess-style: RStudio; -*-
# Jesse Windle, 2023

# Here we try to fit the model generated by `sim_depths_v1.stan`.  We
# will see that the posterior does not concentrate at a point, but
# rather along a surface.

library("rstan")

source(file.path("shared", "functions.R"))


# CONSTANTS
ITER = 800
WARMUP = 400
CHAINS = 2
CORES = 2


# Load - y_list and grid_df
# load(file.path("cache", "ident-sim.RData"))


# Pick a random parameter
idx = sample.int(nrow(grid_df), size=1)
idx

param = grid_df[idx,]
y_data = y_list[[idx]]


# Model
fit_depths_v1 = stan_model(file.path("identifiability", "fit_depths_v1.stan"), model_name="fit_depths_v1", verbose=TRUE)


# Set parameters
N = length(y_data)
M = 1
group = rep(1, N)

dat = list(
  N=N,
  M=M,
  K=3,
  group=group,
  r=8,
  mu_dx_prior_mean = 3.,
  mu_dx_prior_std = 0.1,
  mu_dm_prior_mean = -0.5,
  mu_dm_prior_cond_slope = -1./12,
  mu_dm_prior_cond_std = 0.3,
  sig_dx_prior_mean = 0.1,
  sig_dx_prior_std = 0.05,
  sig_dm_prior_mean = 0.3,
  sig_dm_prior_std = 0.3,
  y = y_data
)


# Fit it - this will take a while
samp = sampling(
  fit_depths_v1,
  data=dat,
  chains=CHAINS,
  cores=CORES,
  iter=ITER,
  warmup=WARMUP,
  init_r=1,
  control = list(max_treedepth=10, adapt_delta=0.25)
)


# Pairs plot --- we see that the sampler seems to be moving a surface in (mu_dx, mu_dm) space.
pairs(samp, c("mu_dx", "mu_dm"))
