rad: &rad 8.0
# min_depth: &min_depth -16.32
# max_depth: &max_depth -2.43
# log_min: &log_min 0.88
# log_max: &log_max 2.8
min_depth: &min_depth -17.085714
max_depth: &max_depth -1.657143
log_min: &log_min 0.505095
log_max: &log_max 2.838143
min_depth_2: &min_depth_2 -24.
max_depth_2: &max_depth_2 -1.
log_min_2: &log_min_2 0.0
log_max_2: &log_max_2 3.18
# min_angle: &min_angle -1.11478
# max_angle: &max_angle -0.2
# min_angle: &min_angle -1.25
# max_angle: &max_angle -0.15
min_angle: &min_angle -1.183
max_angle: &max_angle -0.154
mu_dx_1k: &mu_dx_1k 4.0
mu_dx_2k: &mu_dx_2k 2.67
mu_dx_3k: &mu_dx_3k 2.0
frac_var: &frac_var 0.9
write: True
# models_to_run: ["m21_1k", "m21_2k", "m21_3k"]
# simulations_to_run: ["m21_1k", "m21_2k", "m21_3k"]
models_to_run: ["m08", "m09", "m10_1k", "m10_2k", "m10_3k", "m14", "m21_1k", "m21_2k", "m21_3k"]
simulations_to_run: ["m08_1k", "m08_2k", "m08_3k", "m09_1k", "m09_2k", "m09_3k", "m10_1k", "m10_2k", "m10_3k", "m14_1k", "m14_2k", "m14_3k", "m21_1k", "m21_2k", "m21_3k"]
# simulations_to_run: ["m08_2k", "m09_2k", "m10_2k", "m14_2k", "m21_2k"]
data_frac: 1.0
crop: "Wheat"
mcmc: &default_mcmc
  iter: 7000
  warmup: 3000
  chains: 4
  cores: 4
models:
  m08:
    stan_file_id: "m08"
    transform:
      log_transform: False
      offset: 0
    constants:
      r: *rad
      min_depth: *min_depth
      max_depth: *max_depth
    prior:
      mu_y_prior_mean: -8.0
      mu_y_prior_std: 8.0
      sig_y_prior_mean: 8.0
      sig_y_prior_std: 8.0
    keep_pars: ["mu_y", "sig_y"]
    mcmc: *default_mcmc
  m09:
    stan_file_id: "m09"
    transform:
      log_transform: False
      offset: 0
    constants:
      r: *rad
      min_depth: *min_depth
      max_depth: *max_depth
      frac_var: *frac_var
    prior:
      tilde_mu_prior_mean: -8.0
      tilde_mu_prior_std: 8.0
      tilde_sig_prior_mean: 8.0
      tilde_sig_prior_std: 8.0
    keep_pars: ["tilde_mu", "tilde_sig"]
    mcmc: *default_mcmc
  m10_1k:
    stan_file_id: "m10"
    transform:
      log_transform: False
      offset: 0
    constants:
      r: *rad
      mu_dx: *mu_dx_1k
    prior:
      mu_y_prior_mean: -8.0
      mu_y_prior_std: 4.0
      sig_y_prior_mean: 4.0
      sig_y_prior_std: 4.0
      shape_dm_prior_mean: 0.0
      shape_dm_prior_std: 4
    keep_pars: ["mu_y", "sig_y", "mu_dm", "sig_dm", "shape_dm"]
    mcmc: *default_mcmc
  m10_2k:
    stan_file_id: "m10"
    transform:
      log_transform: False
      offset: 0
    constants:
      r: *rad
      mu_dx: *mu_dx_2k
    prior:
      mu_y_prior_mean: -8.0
      mu_y_prior_std: 4.0
      sig_y_prior_mean: 4.0
      sig_y_prior_std: 4.0
      shape_dm_prior_mean: 0.0
      shape_dm_prior_std: 4
    keep_pars: ["mu_y", "sig_y", "mu_dm", "sig_dm", "shape_dm"]
    mcmc: *default_mcmc
  m10_3k:
    stan_file_id: "m10"
    transform:
      log_transform: False
      offset: 0
    constants:
      r: *rad
      mu_dx: *mu_dx_3k
    prior:
      mu_y_prior_mean: -8.0
      mu_y_prior_std: 4.0
      sig_y_prior_mean: 4.0
      sig_y_prior_std: 4.0
      shape_dm_prior_mean: 0.0
      shape_dm_prior_std: 4
    keep_pars: ["mu_y", "sig_y", "mu_dm", "sig_dm", "shape_dm"]
    mcmc: *default_mcmc
  m14:
    stan_file_id: "m08"
    transform:
      log_transform: True
      offset: 0
    constants:
      r: *rad
      min_depth: *log_min
      max_depth: *log_max
    prior:
      mu_y_prior_mean: 1.
      mu_y_prior_std: 2.
      sig_y_prior_mean: 0.5
      sig_y_prior_std: 2.
    keep_pars: ["mu_y", "sig_y"]
    mcmc: *default_mcmc
  m20_1k:
    stan_file_id: "m20"
    transform:
      log_transform: False
      offset: 0
    constants:
      r: *rad
      min_angle: *min_angle
      max_angle: *max_angle
      lba: *min_angle
      uba: *max_angle
      mu_dx: *mu_dx_1k
    prior:
      mu_yp_mean: 9.
      mu_yp_std: 3.
      sig_yp_mean: 5.
      sig_yp_std: 3.
      xi_start_mean: 1.75
      xi_start_std: 0.01
    keep_pars: ["mu_yp", "sig_yp", "xi_start"]
    mcmc: *default_mcmc
  m21_1k:
    stan_file_id: "m21"
    transform:
      log_transform: False
      offset: 0
    constants:
      r: *rad
      min_angle: -1.15
      max_angle: -0.20
      mu_dx: *mu_dx_1k
      frac_start_lower: 0.7
      frac_start_upper: 0.97
    prior:
      mu_yp_mean: 9.
      mu_yp_std: 4.
      sig_yp_mean: 0.
      sig_yp_std: 1.
      lba_width: 0.10
      uba_width: 0.15
    keep_pars: ["mu_yp", "sig_yp", "lba", "uba", "start_frac"]
    mcmc: *default_mcmc
  m21_2k:
    stan_file_id: "m21"
    transform:
      log_transform: False
      offset: 0
    constants:
      r: *rad
      min_angle: -1.15
      max_angle: -0.20
      mu_dx: *mu_dx_2k
      frac_start_lower: 0.7
      frac_start_upper: 0.97
    prior:
      mu_yp_mean: 9.
      mu_yp_std: 4.
      sig_yp_mean: 0.
      sig_yp_std: 1.
      lba_width: 0.10
      uba_width: 0.15
    keep_pars: ["mu_yp", "sig_yp", "lba", "uba", "start_frac"]
    mcmc: *default_mcmc
  m21_3k:
    stan_file_id: "m21"
    transform:
      log_transform: False
      offset: 0
    constants:
      r: *rad
      min_angle: -1.15
      max_angle: -0.20
      mu_dx: *mu_dx_3k
      frac_start_lower: 0.7
      frac_start_upper: 0.97
    prior:
      mu_yp_mean: 9.
      mu_yp_std: 4.
      sig_yp_mean: 0.
      sig_yp_std: 1.
      lba_width: 0.10
      uba_width: 0.15
    keep_pars: ["mu_yp", "sig_yp", "lba", "uba", "start_frac"]
    mcmc: *default_mcmc
simulations:
  m08_1k:
    model: "m08"
    sim_info:
      mu_dx: *mu_dx_1k
    pars: ["mu_y", "sig_y"]
  m08_2k:
    model: "m08"
    sim_info:
      mu_dx: *mu_dx_2k
    pars: ["mu_y", "sig_y"]
  m08_3k:
    model: "m08"
    sim_info:
      mu_dx: *mu_dx_3k
    pars: ["mu_y", "sig_y"]
  m09_1k:
    model: "m09"
    sim_info:
      mu_dx: *mu_dx_1k
    pars: ["tilde_mu", "tilde_sig"]
  m09_2k:
    model: "m09"
    sim_info:
      mu_dx: *mu_dx_2k
    pars: ["tilde_mu", "tilde_sig"]
  m09_3k:
    model: "m09"
    sim_info:
      mu_dx: *mu_dx_3k
    pars: ["tilde_mu", "tilde_sig"]
  m10_1k:
    model: "m10_1k"
    sim_info:
    pars: ["mu_dm", "sig_dm", "shape_dm"]
  m10_2k:
    model: "m10_2k"
    sim_info:
    pars: ["mu_dm", "sig_dm", "shape_dm"]
  m10_3k:
    model: "m10_3k"
    sim_info:
    pars: ["mu_dm", "sig_dm", "shape_dm"]
  m14_1k:
    model: "m14"
    sim_info:
      mu_dx: *mu_dx_1k
    pars: ["mu_y", "sig_y"]
  m14_2k:
    model: "m14"
    sim_info:
      mu_dx: *mu_dx_2k
    pars: ["mu_y", "sig_y"]
  m14_3k:
    model: "m14"
    sim_info:
      mu_dx: *mu_dx_3k
    pars: ["mu_y", "sig_y"]
  m15_1k:
    model: "m08"
    sim_info:
      mu_dx: *mu_dx_1k
      min_depth: *min_depth_2
      max_depth: *max_depth_2
    pars: ["mu_y", "sig_y"]
  m15_2k:
    model: "m08"
    sim_info:
      mu_dx: *mu_dx_2k
      min_depth: *min_depth_2
      max_depth: *max_depth_2
    pars: ["mu_y", "sig_y"]
  m15_3k:
    model: "m08"
    sim_info:
      mu_dx: *mu_dx_3k
      min_depth: *min_depth_2
      max_depth: *max_depth_2
    pars: ["mu_y", "sig_y"]
  m18_1k:
    model: "m14"
    sim_info:
      mu_dx: *mu_dx_1k
      min_depth: *log_min_2
      max_depth: *log_max_2
    pars: ["mu_y", "sig_y"]
  m18_2k:
    model: "m14"
    sim_info:
      mu_dx: *mu_dx_2k
      min_depth: *log_min_2
      max_depth: *log_max_2
    pars: ["mu_y", "sig_y"]
  m18_3k:
    model: "m14"
    sim_info:
      mu_dx: *mu_dx_3k
      min_depth: *log_min_2
      max_depth: *log_max_2
    pars: ["mu_y", "sig_y"]
  m20_1k:
    model: "m20_1k"
    sim_info:
    pars: ["mu_yp", "sig_yp", "xi_start"]
  m21_1k:
    model: "m21_1k"
    sim_info:
    pars: ["mu_yp", "sig_yp", "lba", "uba", "start_frac"]
  m21_2k:
    model: "m21_2k"
    sim_info:
    pars: ["mu_yp", "sig_yp", "lba", "uba", "start_frac"]
  m21_3k:
    model: "m21_2k"
    sim_info:
    pars: ["mu_yp", "sig_yp", "lba", "uba", "start_frac"]
