rad: &rad 8.0
min_depth: &min_depth -16.32
max_depth: &max_depth -2.43
mu_dx_1k: &mu_dx_1k 4.0
mu_dx_2k: &mu_dx_2k 2.67
mu_dx_3k: &mu_dx_3k 2.0
frac_var: &frac_var 0.50
write: False
models_to_run: ["m08", "m09", "m10_1k", "m10_2k", "m10_3k"]
simulations_to_run: ["m08_1k", "m08_2k", "m08_3k"]
data_frac: 0.2
crop: "Corn"
mcmc: &default_mcmc
  iter: 800
  warmup: 400
  chains: 1
  cores: 1
models:
  m08:
    stan_file_id: "m08"
    prior_info:
      r: *rad
      min_depth: *min_depth
      max_depth: *max_depth
      mu_y_prior_mean: -8.0
      mu_y_prior_std: 8.0
      sig_y_prior_mean: 8.0
      sig_y_prior_std: 8.0
    keep_pars: ["mu_y", "sig_y"]
    mcmc: *default_mcmc
  m09:
    stan_file_id: "m09"
    prior_info:
      r: *rad
      min_depth: *min_depth
      max_depth: *max_depth
      tilde_mu_prior_mean: -8.0
      tilde_mu_prior_std: 8.0
      tilde_sig_prior_mean: 8.0
      tilde_sig_prior_std: 8.0
      frac_var: *frac_var
    keep_pars: ["tilde_mu", "tilde_sig"]
    mcmc: *default_mcmc
  m10_1k:
    stan_file_id: "m10"
    prior_info:
      r: *rad
      mu_dx: *mu_dx_1k
      mu_y_prior_mean: -8.0
      mu_y_prior_std: 4.0
      sig_y_prior_mean: 4.0
      sig_y_prior_std: 4.0
      shape_dm_prior_mean: 0.0
      shape_dm_prior_std: 4
    keep_pars: ["mu_y", "sig_y", "mu_dm", "sig_dm", "shape_dm"]
    mcmc: *default_mcmc
  m10_2k:
    stan_file_id: "m10"
    prior_info:
      r: *rad
      mu_dx: *mu_dx_2k
      mu_y_prior_mean: -8.0
      mu_y_prior_std: 4.0
      sig_y_prior_mean: 4.0
      sig_y_prior_std: 4.0
      shape_dm_prior_mean: 0.0
      shape_dm_prior_std: 4
    keep_pars: ["mu_y", "sig_y", "mu_dm", "sig_dm", "shape_dm"]
    mcmc: *default_mcmc
  m10_3k:
    stan_file_id: "m10"
    prior_info:
      r: *rad
      mu_dx: *mu_dx_3k
      mu_y_prior_mean: -8.0
      mu_y_prior_std: 4.0
      sig_y_prior_mean: 4.0
      sig_y_prior_std: 4.0
      shape_dm_prior_mean: 0.0
      shape_dm_prior_std: 4
    keep_pars: ["mu_y", "sig_y", "mu_dm", "sig_dm", "shape_dm"]
    mcmc: *default_mcmc
simulations:
  m08_1k:
    model: "m08"
    sim_info:
      r: *rad
      mu_dx: *mu_dx_1k
      min_depth: *min_depth
      max_depth: *max_depth
    pars: ["mu_y", "sig_y"]
  m08_2k:
    model: "m08"
    sim_info:
      r: *rad
      mu_dx: *mu_dx_2k
      min_depth: *min_depth
      max_depth: *max_depth
    pars: ["mu_y", "sig_y"]
  m08_3k:
    model: "m08"
    sim_info:
      r: *rad
      mu_dx: *mu_dx_3k
      min_depth: *min_depth
      max_depth: *max_depth
    pars: ["mu_y", "sig_y"]
  m09_1k:
    model: "m09"
    sim_info:
      r: *rad
      mu_dx: *mu_dx_1k
      min_depth: *min_depth
      max_depth: *max_depth
      frac_var: *frac_var
    pars: ["tilde_mu", "tilde_sig"]
  m09_2k:
    model: "m09"
    sim_info:
      r: *rad
      mu_dx: *mu_dx_2k
      min_depth: *min_depth
      max_depth: *max_depth
      frac_var: *frac_var
    pars: ["tilde_mu", "tilde_sig"]
  m09_3k:
    model: "m09"
    sim_info:
      r: *rad
      mu_dx: *mu_dx_3k
      min_depth: *min_depth
      max_depth: *max_depth
      frac_var: *frac_var
    pars: ["tilde_mu", "tilde_sig"]
  m10_1k:
    model: "m10_1k"
    sim_info:
      r: *rad
      mu_dx: *mu_dx_1k
    pars: ["mu_dm", "sig_dm", "shape_dm"]
  m10_2k:
    model: "m10_2k"
    sim_info:
      r: *rad
      mu_dx: *mu_dx_2k
    pars: ["mu_dm", "sig_dm", "shape_dm"]
  m10_3k:
    model: "m10_3k"
    sim_info:
      r: *rad
      mu_dx: *mu_dx_3k
    pars: ["mu_dm", "sig_dm", "shape_dm"]
